---
name: push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  registry: ghcr.io

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        platform:
          - debian11
          - opensuse15
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{ defaultContext }}:platforms/${{ matrix.platform }}"
          tags: ${{ env.registry }}/${{ github.repository }}/${{ matrix.platform }}:latest
          cache-to: type=gha,scope=$GITHUB_REF_NAME-${{ matrix.platform }}
          cache-from: type=gha,scope=$GITHUB_REF_NAME-${{ matrix.platform }}

