---
name: push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  registry: ghcr.io

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: List platforms
        id: list-platforms
        run: |
          echo "platforms=" >> $GITHUB_OUTPUT
          ls platforms | jq -srR 'split("\n") | map(select(. != "")) | @json' >> $GITHUB_OUTPUT
    outputs:
      platforms: ${{ steps.list-platforms.outputs.platforms }}
  build-push:
    runs-on: ubuntu-latest
    needs: prepare-matrix
    permissions:
      contents: read
      packages: write
    strategy:
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.platforms) }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{ defaultContext }}:platforms/${{ matrix.platform }}"
          tags: ${{ env.registry }}/${{ github.repository }}/${{ matrix.platform }}:latest
          cache-to: type=gha,scope=$GITHUB_REF_NAME-${{ matrix.platform }}
          cache-from: type=gha,scope=$GITHUB_REF_NAME-${{ matrix.platform }}

