---
name: push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  registry: ghcr.io
  platform: debian11

jobs:
  build-push:
    runs-on: ubuntu:latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{ defaultContext }}:platforms/${{ env.platform }}"
          tags: ${{ env.registry }}/${{ github.repository }}/${{ env.platform }}:latest
          cache-to: type=gha,scope=$GITHUB_REF_NAME-${{ env.platform }}
          cache-from: type=gha,scope=$GITHUB_REF_NAME-${{ env.platform }}

